name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build binaries
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        LDFLAGS="-X 'github.com/crisecheverria/codequest/cmd.Version=$VERSION'"
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="$LDFLAGS" -o codequest-linux-amd64 main.go
        GOOS=linux GOARCH=arm64 go build -ldflags="$LDFLAGS" -o codequest-linux-arm64 main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags="$LDFLAGS" -o codequest-darwin-amd64 main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags="$LDFLAGS" -o codequest-darwin-arm64 main.go
        GOOS=windows GOARCH=amd64 go build -ldflags="$LDFLAGS" -o codequest-windows-amd64.exe main.go
        
        # Create checksums
        sha256sum codequest-* > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          codequest-linux-amd64
          codequest-linux-arm64
          codequest-darwin-amd64
          codequest-darwin-arm64
          codequest-windows-amd64.exe
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}